### PR TITLE
Escape HTML characters in the indicator search variable tooltip.

### LINKED ISSUE #1524: Documentation: Search - indicator variable tooltip
### Generic Issue

* xclim version: 0.46.0
* Python version:
* Operating System:

### Description
The search button has the wrong tooltip for, for example, lat ("Latitude coordinate. If None and method in ["). This is because the documentation uses double-quotes, which are a special character in HTML. This also risks causing invalid webpages - thankfully it seems to display the page in firefox.

### What I Did
https://xclim.readthedocs.io/en/stable/indicators.html and hover over lat variable for Biologically effective degree days

### What I Received

```
<button class="indVarname" title="Latitude coordinate. If None and method in [" gladstones",="" "icclim"],="" a="" cf-conformant="" "latitude"="" field="" must="" be="" available="" within="" the="" passed="" dataarray."="" alt="Latitude coordinate. If None and method in [">lat</button>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by huard**
### Pull Request Checklist:
- [x] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes #1524
- [ ] Tests for the changes have been added (for bug fixes / features)
  - [ ] (If applicable) Documentation has been added / updated (for bug fixes / features)
- [ ] CHANGES.rst has been updated (with summary of main changes)
  - [ ] Link to issue (:issue:`number`) and pull request (:pull:`number`) has been added

### What kind of change does this PR introduce?

* Adds a JS function to escape HTML characters.

### CODE REVIEW

File: docs/_static/indsearch.js [hunk 1]
```diff
@@ -55,7 +58,10 @@ function makeKeywordLabel(ind) {
 function makeVariableList(ind) {
     /* Print list of variables and include mouse-hover tooltip with variable description. */
     return Object.entries(ind.vars).map((kv) => {
-        const tooltip = `<button class="indVarname" title="${kv[1]}" alt="${kv[1]}">${kv[0]}</button>`;
+        /* kv[0] is the variable name, kv[1] is the variable description. */
+        /* Convert kv[1] to a string literal */
+        const text = escapeHTML(kv[1]);
+        const tooltip = `<button class="indVarname" title="${text}" alt="${text}">${kv[0]}</button>`;
```
Comment (SarahG-579462) [inline docs/_static/indsearch.js:64]: Looks good, we should probably use the function elsewhere too, just as a safety check. 

For example, `j <i --> test [rest of doc...]` renders as "j _test [rest of doc...]_"

**Review by SarahG-579462 — APPROVED** [review]
Approved, recommend using the function elsewhere as well though!
